{% set version = "1.1.0" %}

package:
  name: trame-color-opacity-editor
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/trame-color-opacity-editor/trame_color_opacity_editor-{{ version }}.tar.gz
  sha256: 44f1ee7a6e08930fa4e51ee65a8118e23e6fced9395e0a223402dc9eb3c43a3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - trame-client >=3.10

test:
  imports:
    - trame_color_opacity_editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/Kitware/trame-color-opacity-editor
  summary: A trame package implementing the Paraview/Tomviz color-opacity editor.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alesgenova
    - psavery
    - jourdain
